name: Full Auto AKS Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Backend Exists
        run: echo "Backend already created. Skipping backend provisioning."

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install kubectx & kubens
        run: |
          sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
          sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
          sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens

      - name: Get AKS Credentials
        run: |
          RG=$(terraform -chdir=terraform output -raw resource_group_name)
          AKS=$(terraform -chdir=terraform output -raw aks_name)
          az aks get-credentials -g $RG -n $AKS --overwrite-existing

      - name: Verify Kubernetes Access
        run: kubectl get nodes
